version: '3.8'

services:
  mongo:
    image: 'mongo:7.0.5'
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/var/lib/mongodb/data

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    depends_on:
      - mongo
    ports:
      - '8081:8081'
    volumes:
      - data:/data/db

  processor:
    container_name: processor
    build:
      context: .
      dockerfile: apps/processor/Dockerfile
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://mongo:27017/products
    ports:
      - '5000:5000'

  uploader:
    container_name: uploader
    build:
      context: .
      dockerfile: apps/uploader/Dockerfile
    env_file:
      - .env
    ports:
      - '3000:3000'

volumes:
  mongo-data:
  data:
