version: '3.8'

services:
  mongo:
    image: 'mongo:7.0.5'
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/var/lib/mongodb/data

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    depends_on:
      - mongo
    ports:
      - '8081:8081'
    volumes:
      - data:/data/db

volumes:
  mongo-data:
  data:
